/** Labels drawn inside the demo canvases and their control panels. */
import type { Code } from '../data/types.ts';
import { f1, years } from './calc.ts';

/** How demos introduce each bond: a short handle plus one line of context. */
export const BOND_LABELS: Partial<Record<Code, { short: string; line: string }>> = {
  BOND36: { short: "4.5 Feb'36", line: '主线债 · 2006 年发的 30 年期 Bond' },
  NOTE36F: { short: "4.125 Feb'36", line: '同一天到期的 Note · 票息更低' },
  SP36: { short: "STRIPS Feb'36", line: '本金条 · 零息 Zero-coupon' },
  BILL27: { short: "Bill Sep'27", line: '国库券 Bill · 零息 · 不到一年到期' },
  BOND30: { short: "Bond 6.25 May'30", line: '2000 年发的老债 · 溢价 Premium' },
  NOTE36A: { short: "Note 4.625 Aug'36", line: '2026 年 8 月新发的 10 年期 · 最活跃' },
  SP43: { short: "STRIPS Nov'43", line: '本金条 · 零息 · order.png 里买的那只' },
  TIPS56: { short: "TIPS 2.375 Feb'56", line: '通胀保值债 · 收益率是实际收益率' },
  NOTE36M: { short: "Note 4.375 May'36", line: '2036 年 5 月到期的 Note' },
  NSP36M: { short: "Note STRIPS May'36", line: '从 Note 拆出的本金条' },
  SI46: { short: "STRIPS Int May'46", line: '利息条 · 比本金条收益率略高' },
  SP28A: { short: "STRIPS Aug'28", line: '本金条 · 还剩 1.9 年' },
  SP28: { short: "STRIPS Nov'28", line: '本金条 · 还剩 2.1 年' },
  SI28: { short: "STRIPS Int Nov'28", line: '利息条 · 还剩 2.1 年' },
  SP29: { short: "STRIPS Feb'29", line: '本金条 · 还剩 2.4 年' },
  SP48: { short: "STRIPS Aug'48", line: `本金条 · 零息 · 还剩 ${f1(years('SP48'))} 年` },
};

export const cashflowText = {
  stageTitle: '现金流时间轴 Cash Flow Timeline',
  stageSub: '{name} · 面值 Face {face}',
  today: '今天 Today',
  maturity: '到期 Maturity',
  eachCoupon: '每次票息 {amt}',
  refLine: "4.5 Feb'36 的票息高度",
  principal: '本金 Principal {amt}',
  notToScale: '本金柱不按比例',
  zeroNote: '中间一分钱不付，到期一次给本金 Nothing until maturity',
  tapHint: '点一根柱子，看日期和金额 Tap a bar',
  pickBond: '选一只债 Pick a bond',
  pickFace: '面值 Face Value',
  selected: '这一笔 This payment',
  couponOnly: '票息 Coupon',
  couponAndPrincipal: '票息 + 本金 Coupon + Principal',
  principalOnly: '本金 Principal',
  per100: '每 100 面值 per 100：{amt}',
  statPayments: '剩余付款次数 Payments left',
  statEach: '每次票息 Each coupon',
  statPrincipal: '到期还本金 Principal at maturity',
  none: '—',
  revealRunning: '累计票息 Coupons so far {sum}（{i} / {n}）',
  revealDone: '{n} × {each} = {sum}',
  revealGuess: '你押 Your bet {guess}',
  principalExcluded: '本金不算 Not counted',
  aria: '现金流柱状图，每根柱子是一次付款 Cash flow bars, one per payment',
};

export const seesawText = {
  stageTitle: '价格 ↔ 收益率 Price ↔ Yield',
  stageSub: '{name} · 票息 Coupon {c}% · 到期 Maturity {m}',
  price: '价格 Price',
  yield: '收益率 Yield',
  higher: '利率比今天高 → 价格比今天低',
  lower: '利率比今天低 → 价格比今天高',
  today: '今天 Today：{p} ↔ {y}',
  axisX: '到期收益率 Yield to Maturity →',
  axisY: '价格 Price',
  par: '面值 Par = 100',
  todayMarker: 'IBKR 今天 Today {p}',
  slider: '市场收益率 Market Yield（拖动 drag）',
  ytm: '到期收益率 YTM',
  priceRow: '价格 Price（每 100 面值 per 100）',
  status: '状态 Status',
  discount: '折价 Discount',
  premium: '溢价 Premium',
  parPill: '平价 Par',
  whyDiscount: '收益率 {y} 高于票息 {c}%，所以价格低于 100。',
  whyPremium: '收益率 {y} 低于票息 {c}%，所以价格高于 100。',
  whyPar: '收益率等于票息，价格就是 100。',
  reset: '回到今天 Back to Today（{p} ↔ {y}）',
  breakdownTitle: '持有到期，你的钱从哪来 Where the Return Comes From',
  coupon: '每年票息 Coupon',
  pull: '到期补回面值 Pull to Par',
  currentYield: '当前收益率 Current Yield（票息 ÷ 价格）',
  ytmBoth: '到期收益率 YTM（两者合起来）',
  answer: '答案 Answer {p}',
  guess: '你押 Your bet {p}',
  aria: '上：跷跷板，一头价格一头收益率。下：价格随收益率变化的曲线，可以左右拖。',
};

export const multiText = {
  stageTitle: '四只债，同一个利率变动 Four Bonds, One Rate Move',
  stageSub: '横轴：所有收益率一起变多少；纵轴：价格变百分之几。在图上左右拖也可以。',
  axisX: '收益率变动 Yield Change（bp）→',
  axisY: '价格变化 Price Change',
  slider: '收益率整体变动 Parallel Shift',
  colBond: '债 Bond',
  colYears: '剩余年 Yrs',
  colNow: '今价 Now',
  colNew: '新价 New',
  colChange: '变化 Chg',
  colDuration: '久期 Dur',
  note: '修正久期 Modified Duration：利率变 1%，价格大约变百分之几（引擎算的）。今价来自 2026-09-29 IBKR 屏幕。',
  aria: '四只债的价格变化随收益率平移变化的曲线，可以左右拖。',
};

export const pullText = {
  stageTitle: '拉回面值 Pull to Par',
  stageSub: '收益率一直不变：{name} 每天的价格，和你攒下的票息',
  axisPrice: '价格 Price（收益率不变）',
  axisCoupons: '累计票息 Coupons so far（每 100 面值）',
  par: '面值 Par = 100',
  today: '今天 {p}',
  maturity: '到期 100',
  at: '{date} · {p}',
  couponsSoFar: '累计票息 {c}',
  pickBond: '选一只债 Pick a bond',
  slider: '日期 Date（拖动 drag）',
  play: '▶ 播放到到期 Play to maturity',
  back: '回到今天 Back to Today',
  yearsFromNow: '距今 {n} 年',
  rowYield: '到期收益率 YTM（不变）',
  rowPrice: '价格 Price',
  rowVsToday: '比今天 vs Today',
  rowCoupons: '累计票息 Coupons received',
  rowTotal: '价格变化 + 票息 Price change + coupons',
  note: '每 100 面值计。到期那天价格正好 100。',
  answer: '答案 Answer {p}',
  guess: '你押 Your bet {p}',
  aria: '上：收益率不变时价格随时间的路径。下：累计收到的票息。可以左右拖。',
};

export const accruedText = {
  stageTitle: '净价、全价与应计利息 Clean, Dirty, Accrued',
  stageSub: '{name} · 收益率不变 · 拖结算日看锯齿',
  dirty: '全价 Dirty',
  clean: '净价 Clean',
  zeroShort: '净价 = 全价',
  couponDay: '付息日 Coupon date',
  today: '今天结算 9/30',
  accruedTag: '应计 Accrued {a}',
  ticketTitle: 'Order Ticket（仿第二步 Preview）',
  ticketHead: 'Buy {q} US-T for about ~ {total} USD',
  rowQty: 'THOUSAND FACE VALUE',
  rowPrice: 'Limit Price（净价 Clean）',
  rowAmount: 'Amount',
  rowCommission: 'Commissions & Fees (est.)',
  rowAccrued: 'Accrued Interest (est.)',
  rowTotal: 'Total',
  rowShare: '佣金占实付 Commission share',
  usd: '{v} USD',
  ticketNote: '佣金按 IBKR 官方费率：面值的 0.2bp，最低 $5。真实下单页会显示一个预估区间 5.00 … 8.00。',
  pickBond: '选一只债 Pick a bond',
  dateSlider: '结算日 Settlement date',
  faceSlider: '数量 THOUSAND FACE VALUE',
  faceValue: '{k}（= {usd} 面值）',
  backToday: '回到今天结算 Back to 9/30',
  lastCoupon: '上次付息日 Last coupon',
  nextCoupon: '下次付息日 Next coupon',
  daysAccrued: '已过天数 Days accrued',
  daysOf: '{d} / {n} 天',
  accruedPer100: '应计 Accrued（每 100 面值）',
  accruedPer1000: '应计 Accrued（每 $1,000 面值）',
  noCoupons: '零息债没有付息日 No coupon dates',
  aria: '结算日从 2026-08-15 到 2027-05-15：净价几乎是平线，全价每天爬升、付息日掉回。',
};

export const quoteText = {
  stageTitle: 'Bid / Ask：你买在哪、卖在哪 Where You Buy and Sell',
  stageSub: '上：仿 IBKR 详情页头部。下：五只债的点差。',
  tag: 'US-T  BONDDESKG',
  ccy: 'USD',
  ask: 'Ask',
  bid: 'Bid',
  buy: 'Buy',
  sell: 'Sell',
  approxNote: '带 ≈ 的 ask 价在截图里被截断，按 IBKR 的 ask 收益率反算',
  bought: '你买在 Ask {p}，锁定收益率 {y}',
  sold: '你卖在 Bid {p}',
  soldAlone: '你卖在 Bid {p}（前提是你手里有这只债）',
  roundTrip: '一买一卖：{face} 面值亏 {loss}',
  chartTitle: '点差 Spread（每 100 面值）· 每 $100,000 面值一买一卖的成本',
  barValue: '{p} · {usd}',
  pickBond: '选一只债 Pick a bond',
  faceSlider: '面值 Face（千 THOUSAND FACE VALUE）',
  faceValue: '{k}（= {usd}）',
  logTitle: '你的成交 Your fills',
  logBuy: '买入 Bought',
  logSell: '卖出 Sold',
  logLoss: '来回亏 Round-trip loss',
  none: '—',
  reset: '重来 Reset',
  spreadRow: '点差 Spread',
  spreadYield: '收益率差 Yield gap',
  aria: '仿 IBKR 详情页头部的 Ask / Bid 报价，和五只债的点差条形图。',
};

export const curveText = {
  stageTitle: '收益率曲线 Yield Curve · 2026-09-29',
  stageSub: '横轴：还剩几年到期；纵轴：到期收益率（IBKR Bid / Ask 收益率的中点）。点一个点看是哪只债。',
  axisX: '剩余年限 Years to Maturity →',
  axisY: '收益率 Yield',
  today: '今天 Today',
  inferred: '30 年：推的 inferred',
  years: '{n} 年',
  pickTitle: '点中的债 Selected',
  pickHint: '点曲线上的任一个点 Tap a dot',
  rowType: 'Treasury Type',
  rowMaturity: '到期 Maturity',
  rowYears: '剩余 Years left',
  rowYield: '收益率 Yield（中点 mid）',
  rowBidAsk: 'Bid / Ask 收益率',
  rowPrice: '价格 Price',
  filterTitle: 'Bond Scanner 筛选（仿）Treasury Type',
  filterNote: '选 Note 会带出 Note STRIPS，选 Bond 会带出 Bond STRIPS：IBKR 截图里就是这样。下拉的完整选项没截到，这里只列看到过的。',
  filterNone: 'TIPS 的收益率是实际收益率，画在另一条曲线上（第 11 关）。',
  filterCount: '符合的点 Matches：{n}',
  shiftTitle: '曲线会怎么动 How the curve moves（第 14 关沙盒）',
  shiftP1: '平行上移 Parallel up',
  shiftP2: '平行下移 Parallel down',
  shiftP3: '变陡 Steeper',
  shiftP4: '变平 / 倒挂 Flatter',
  shiftReset: '回到今天 Back to Today',
  shiftDesc: '{name}：1 年以内 {s}，20 年以上 {l}',
  bp: '{n} bp',
  readAt: '{y} 年：{v}',
  guess: '你押 Your bet {v}',
  realShort: 'IBKR 实际 2 年点 Real 2y',
  aria: '2026-09-29 的美国国债收益率曲线，每个点是一只真实的债。',
};

export const sideText = {
  stageTitle: '同一个收益率，三个不同的价格 One Yield, Three Prices',
  stageSubToday: '今天的 IBKR 报价：收益率不一样',
  stageSubSame: '三只都按 {y} 定价',
  axisY: '价格 Price',
  ring: '今天 {p}',
  couponLine: '票息 Coupon {c}',
  maturityLine: '到期 {m}',
  ytmLine: 'YTM {y}',
  rowCoupon: '票息 Coupon',
  rowMaturity: '到期 Maturity',
  rowPrice: '今天价格 Price',
  rowYtm: '到期收益率 YTM（Bid/Ask 中点）',
  rowSpread: '点差 Spread',
  rowSize: 'Size（Bid / Ask）',
  rowIssued: '发行 Issued',
  spreadTiny: '≤0.01',
  modeToday: '今天的 IBKR 报价 Today',
  modeSame: '同一个收益率 Same yield',
  slider: '同一个收益率 Common yield',
  quickNote: '都按 Note 的 {y}',
  quickBond: '都按 BOND36 的 {y}',
  gap: '价差 Price gap：BOND36 − NOTE36F',
  guess: '你押 Your bet {p}',
  /** Issue date and original term: BOND36 and NOTE36F from CLAUDE.md §2.1, NOTE36A from its detail page. */
  issued: { BOND36: '2006 · 30 年期 Bond', NOTE36F: '2026-02 · 10 年期 Note', NOTE36A: '2026-08-17 · 10 年期 Note' },
  aria: '三只 2036 年到期的国债：同一个收益率下各自的价格，和今天 IBKR 的报价。',
};

export const balanceText = {
  stageTitle: '久期天平 Duration Balance',
  stageSub: '砝码 = 每笔现金流折回今天的价值（现值 PV）；支点 = 麦考利久期',
  axisX: '年 Years →',
  fulcrum: '支点 = 久期 {d} 年',
  maturity: '到期 {t} 年',
  macaulay: '麦考利久期 Macaulay Duration',
  modified: '修正久期 Modified Duration',
  dv01: 'DV01（每 $100,000 面值）',
  estimate: '利率升 1%，价格约',
  yieldRow: '收益率 Yield（这只债今天的）',
  preset: '选一只债 Pick a bond',
  zero: '零息 Zero',
  couponSlider: '票息 Coupon',
  yearsSlider: '剩余年限 Years left',
  custom: '自定义 Custom',
  yearsVal: '{n} 年',
  pctVal: '{n}%',
  revealTitle: '收益率降 {d}，{face} 面值：',
  revealEst: '久期估算 Estimate {v}',
  revealAct: '实际 Actual {v}',
  aria: '天平：横梁是时间，砝码是每笔现金流的现值，支点落在麦考利久期上。',
};
